//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace fmspod1.Models
{
    public partial class Zgloszenie
    {
        public int Id { get; set; }
        public System.DateTime Data
        {
            get;
            set;
            //get
            //{
            //    return DateTime.Now;
            //}
            //set
            //{ 

            //}
        }
        public string status
        {
            get;
            set;
            //get
            //{
            //    return "zg³oszona";
            //}
            //set { }
        }
        public string kod_pocztowy { get; set; }
        public string adres { get; set; }
        public string tresc_zgloszenia { get; set; }
        public string zdjecie { get; set; }
        public string komentarz_admina { get; set; }
    }
    
}
